# Define persistent volumes for each MongoDB instance
volumes:
  mongodb_atlas_data:

# Create a dedicated network for MongoDB communication
networks:
  mongodb_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-python-mongodb-service
    networks:
      - mongodb_network
    environment:
      - MONGODB_URI=mongodb://admin:admin@localhost:27027/?directConnection=true
    depends_on:
      - mongodb_atlas

  mongodb_atlas:
    image: mongodb/mongodb-atlas-local:8.0.5-20250808T111358Z
    restart: unless-stopped
    volumes:
      - mongodb_atlas_data:/data/db
    networks:
      - mongodb_network
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27027:27017"
