# Define persistent volumes for each MongoDB instance
volumes:
  mongodb_atlas_data:
  redpanda-data:

# Create a dedicated network for MongoDB communication
networks:
  mongodb_network:
    driver: bridge
  redpanda_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-python-mongodb-service
    networks:
      - mongodb_network
    environment:
      - MONGODB_URI=mongodb://admin:admin@localhost:27027/?directConnection=true
    depends_on:
      - mongodb_atlas
      - redpanda

  mongodb_atlas:
    image: mongodb/mongodb-atlas-local:8.0.5-20250808T111358Z
    restart: unless-stopped
    volumes:
      - mongodb_atlas_data:/data/db
    networks:
      - mongodb_network
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27027:27017"

redpanda:
  command:
    - redpanda
    - start
    - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
    - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
    - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
    - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
    - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
    - --rpc-addr redpanda-0:33145
    - --advertise-rpc-addr redpanda-0:33145
    - --mode dev-container
    - --smp 1
    - --default-log-level=info
  image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
  volumes:
    - redpanda-data:/var/lib/redpanda/data
  networks:
    - redpanda_network
  ports:
    - 18081:18081
    - 18082:18082
    - 19092:19092
    - 19644:9644

redpanda-console:
  image: docker.redpanda.com/redpandadata/console:v3.1.0
  networks:
    - redpanda_network
  entrypoint: /bin/sh
  command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
  environment:
    CONSOLE_LICENSE_TYPE: community
    CONFIG_FILEPATH: /tmp/config.yml
    CONSOLE_CONFIG_FILE: |
      kafka:
        brokers: ["redpanda-0:9092"]
      schemaRegistry:
        enabled: false
        urls: ["http://redpanda-0:8081"]
      redpanda:
        adminApi:
          enabled: false
          urls: ["http://redpanda-0:9644"]
  ports:
    - 8080:8080
  depends_on:
    - redpanda
